chat/authentication/urls.py
from django.conf.urls import url
from .views import RegisterView, LoginView, logout_view

"""
Urls configuration.
1. register/ - registration page, url - register/
2. login/ - login page, url - login/
3. logout/ - logout page, url - logout/

"""
app_name = "authentication"
urlpatterns = [
     url(r'register/$', RegisterView.as_view(), name="register"),
     url(r'login/$', LoginView.as_view(), name="login"),
     url(r'logout/$', logout_view, name="logout"),
]

chat/chat/urls.py
from django.conf.urls import url, include
from homepage.views import HomepageView

urlpatterns = [
    # homepage
    url(r'^$', HomepageView.as_view(), name='homepage'),
    # auth
    url(r'auth/', include('authentication.urls')),
    # chat
    url(r'chat/', include('chat_app.urls')),
]

chat/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf8">
    <title>{% block title %}Simple chat{% endblock title %}</title>
    <!-- Get bootstrap 3.3.7 from cdn-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Extra head -->
    {% block head %}
    {% endblock head %}
</head>
<body>
    <!-- navbar -->
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'homepage' %}">Simple chat</a>
            </div>
            <!-- check if user authenticated -->
            {% if request.user.is_authenticated %}
                <!-- if yes, show button logout -->
                <div class="navbar-right">
                    <a class="navbar-brand" href="{% url 'authentication:logout' %}">Log out</a>
                </div>
            {% endif %}
        </div>
    </nav>
    <!-- Extra navbar -->
    {% block navbar %}
    {% endblock navbar %}
    <!-- content webpage-->
    <div class="container">
    <!-- Extra content -->
    {% block content %}
    {% endblock content %}
    </div>
    <!-- footer -->
    {% block footer %}
    {% endblock footer %}
    <!-- Scripts -->
    <!-- Jquery 3.2.1 from Google cnd -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js">
    </script>
    <!-- Bootstrap scripts from cnd -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous">
    </script>
    <!-- Extra scripts -->
    {% block script %}
    {% endblock script %}
</body>
</html>