chat/authentication/urls.py
from django.conf.urls import url
from .views import RegisterView, LoginView, logout_view

"""
Urls configuration.
1. register/ - registration page, url - register/
2. login/ - login page, url - login/
3. logout/ - logout page, url - logout/

"""
app_name = "authentication"
urlpatterns = [
     url(r'register/$', RegisterView.as_view(), name="register"),
     url(r'login/$', LoginView.as_view(), name="login"),
     url(r'logout/$', logout_view, name="logout"),
]

chat/chat/urls.py
from django.conf.urls import url, include
from homepage.views import HomepageView

urlpatterns = [
    # homepage
    url(r'^$', HomepageView.as_view(), name='homepage'),
    # auth
    url(r'auth/', include('authentication.urls')),
    # chat
    url(r'chat/', include('chat_app.urls')),
]

chat/chat_app/urls.py
from django.conf.urls import url
from .views import ChatView

"""
Urls configuration.
1. '' - char page, url - chat/

"""
app_name = "chat"
urlpatterns = [
    url(r'^$', ChatView.as_view(), name="chat"),
]

chat/homepage/views.py
from django.views.generic import TemplateView


class HomepageView(TemplateView):
    """
    Homepage view.

    Just show homepage template.

    """
    template_name = "homepage/homepage.html"

chat/templates/homepage/homepage.html
<!-- Extends base.html from templates dir-->
{% extends 'base.html' %}
<!-- Load static from staticfiles_dirs-->
{% load staticfiles %}
{% block title %}Homepage{% endblock title %}

{% block head %}
<link href="{% static 'css/styles.css' %}" rel="stylesheet">
{% endblock head %}

{% block content %}
<!-- Aligned on center -->
<div class="col-md-4 col-md-offset-4">
    <!-- check user authenticated -->
    {% if request.user.is_authenticated %}
        <!-- if true, show only chat button -->
        <a href="{% url 'chat:chat' %}">Join chat</a>
    {% else %}
        <!-- if false -->
        <a href="{% url 'authentication:login' %}" type="submit">Log in</a>
        <a href="{% url 'authentication:register' %}" type="submit">Sign in</a>
    {% endif %}
</div>
{% endblock content %}